### ISSUE TITLE
Unable to use "h]set dailyChannel" even as Admin

### ISSUE THREAD

**Issue by timothymhuang** [AustinTi/HolidayBot#4]
Hello. I love this discord bot but I'm unable to change the daily channel, so it sometimes makes the discord bot unusable.

Whenever I run `h]set dailyChannel`, it gives me this error.

![image](https://user-images.githubusercontent.com/59073651/117552727-1a253000-b002-11eb-885d-bd5479e69d2f.png)

I have admin perms in the server.

**Comment by barkloaf** [comment]
hi there, apologies i didn't get to this sooner, i've been quite busy. i'm investigating the situation now, but because these errors are sparse, it may take a while to get it ironed out. if the issue happens often on your server, try testing it out and triggering it; it might help

**Comment by barkloaf** [comment]
i opened issue bwmarrin/discordgo#981 about this. honestly, don't really know if anything will be done about it

**Comment by barkloaf** [comment]
this should be fixed in ffaa015ca1c1ddaa8b6965d8cee72fb15556f5a2 because I use the permissions built into the new interactions API (https://github.com/barkloaf/HolidayBot/blob/master/commands/Set.go#L32), as opposed to referencing the state like previously

I will close this issue for now, but if the problem persists do let me know and we can open this again
